### PR TITLE
Make /set exempt from Django's CSRF middleware

### LINKED ISSUE #32: Forbidden (CSFR token missions or incorrect): /tz_detect/set
When running this on a pretty clean django install I cannot get the POST to work.

I have it setup as below:-

djsite/djsite/Settings.py

```
INSTALLED_APPS = [
    'cals.apps.CalsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tz_detect',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tz_detect.middleware.TimezoneMiddleware',

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

]
```

djsite/djsite/urls.py

```
urlpatterns = [
    url(r'^cals/', include('cals.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^tz_detect/', include('tz_detect.urls')),
]
```

djsite/cals/views.py

```
def index(request):
    now = datetime.datetime.now()
    context = RequestContext(request, {})
    context["now"] = now
    template = loader.get_template('cals/cals_small.html')
    return HttpResponse(template.render(context))
```

djsite/cals/templates/cals/cals_small.html

```
<html>
    <head></head>
    {% load tz_detect %}
    <body>
        It is {% now "jS F Y H:i" %}
        {% tz_detect %}
    </body>
</html>
```

I get the below output from runserver

```
"GET /cals/ HTTP/1.1" 200 510
"GET /static/tz_detect/js/tzdetect.js HTTP/1.1" 200 2643
Forbidden (CSRF token missing or incorrect.): /tz_detect/set/
"POST /tz_detect/set/ HTTP/1.1" 403 2502
```

It's been a long day so I am likely doing something wrong but would appreciate it if you could take a look.

Python 3.6.0
Django version 1.10.5

### PR DESCRIPTION
**Pull request by blag**
Closes #32.

### CODE REVIEW

**Comment by blag** [comment]
The tests have failed only because Django master (which will be 2.0) does not support Python 2.7 so that run errored out.

My PR #34 fixes that, adds Django 1.11 tests, and allows tests against Django master to fail.

**Comment by adamcharnock** [comment]
@bashu, are you ok for this to be merged? It would be ideal to pass the csrf token up in the request, but I'm not too worried as all we are doing is setting the timezone. Would be happy for that to be sorted later.

**Comment by bashu** [comment]
@blag not needed at all, I've provided solution in #32

**Comment by bashu** [comment]
@adamcharnock everything is correct on our side, the cause was misunderstanding how to use ``render`` function

**Pull request closed without merging**
