### PR TITLE
Prefer Intl timezone over offset

### PR DESCRIPTION
**Pull request by jurrian**
There have been some problems with the offset in relation to daylight savings. Since session caching will keep the offset stored for a longer period, a change in daylight savings during this period would show the incorrect timezone.

Therefore, in addition to the offset we also send the actual timezone name (like 'Europe/Amsterdam'). This will take precedence in the view, if empty somehow (which I don't expect happening) it will still fall back to offset. The middleware already accepts this string form to activate, which is covered by tests. The advantage of timezone over offset it that the corresponding tz will change daylight savings automatically.

I found no instructions for minifying the javascript code so I jus t chose something online.

This might also be a fix for some open issues:
adamcharnock/django-tz-detect#23
adamcharnock/django-tz-detect#47
adamcharnock/django-tz-detect#44

### CODE REVIEW

**Comment by secfigo** [comment]
@adamcharnock Is there anything I can do, to help you get this merged?

**Review by bashu — APPROVED** [review]
LGTM

**Comment by jurrian** [comment]
@adamcharnock @mblayman @bashu Any indication when this can be merged? I am running my local branch for half a year now, daylight savings transition went smooth.

**Comment by agusmakmun** [comment]
Alternatively, we can use direct commit hash id for this fixes in `requirements.txt` file:

```
git+https://github.com/adamcharnock/django-tz-detect.git@7e1f6054828c4f6f1921cad10363c988e9e9ee94#egg=django-tz-detect
```

But make sure the `git` is installed.

----

Would be helpful for us if you guys release that changes to pypi as well.

**Comment by m000** [comment]
Bump for new release 🙂

**Comment by jurrian** [comment]
@adamcharnock can you grant me repo permissions to publish a new release?

**Pull request merged**
